version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the Redis container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:redis

    # # Uncomment the next line to use a non-root user for all processes.
    # user: code

    init: true

  redis:
    image: redis:6.2.11-alpine
    restart: unless-stopped
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
