# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend/
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy with rsync
        run: |
          rsync -a -e "ssh -o StrictHostKeyChecking=no" build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.FRONTEND_LOCATION }}
